type = "rust"

[build]
platforms = [
    { target = "x86_64-unknown-linux-gnu", platform = "linux", arch = "amd64" },
    { target = "x86_64-pc-windows-gnu", platform = "windows", arch = "amd64" },
]
